### ISSUE TITLE
ДЗ 1 Интерфейс

### ISSUE THREAD

**Issue by g3tf13ld** [yermochenko/AQA-dev#1]
https://github.com/yermochenko/AQA-dev/blob/f49f54078077ce1d029b684a88cffba70a9052a0/lab-1/View/IConsoleOutput.cs#L3

Неоднозначное имя интерфейса и метода, которые не отражают суть интерфейса и метода. И посмотрите пожалуйста нейминг конвеншн в C# - почти все интерфейсы оканчиваются на -able. Мои варианты имени интерфейса и метода IDisplayable and DisplayInfo(). Необязательно к исполнению, но обязательно принять к сведению.

**Comment by ValeryiaLukyanava** [comment]
Не критично. Может быть закрыто. Название интерфейса - допустимое C# Naming Conventions

**Comment by yermochenko** [comment]
Я всё же переименовал интерфейс и метод. Правда с code convention в C# мне не всё понятно. Наверное, немного "мешает" опыт работы с Java. В ней интерфейсы не обязательно заканчиваются на -able. Есть интерфейсы на -or (Iterator, Comparator). Я уж не говорю о коллекциях (интерфейсы Collection, List, Map и т.д.). А в C# меня смущает, что все интерфейсы должны начинаться с префикса I. Это вроде бы должно однозначно показывать, что бы работаем с интерфейсом, и наличие суффиксов вроде -able уже мало информации добавляют.

**Comment by ValeryiaLukyanava** [comment]
Да, Сергей Александрович, все верно - замечание Павла не актуально и уже закрыто.
