### ISSUE TITLE
ДЗ1 IReportGenerator

### ISSUE THREAD

**Issue by g3tf13ld** [yermochenko/AQA-dev#4]
https://github.com/yermochenko/AQA-dev/blob/f49f54078077ce1d029b684a88cffba70a9052a0/lab-1/View/IReportGenerator.cs#L8

Имя интерфейса IReportGenerator, а метод OutputReport. Имя метода не соответствует выполняемой функции. Могу предложить Generate или GenerateReport. Output крайне редко используется как глагол. Также интерфейсы желатeльно вынести в отдельную папку, например Interfaces.

**Comment by yermochenko** [comment]
Спасибо. Тут исправил. Тольек в отдельную папку не выносил. Если в проекте на разных уровнях будет большое количество интерфейсов, назначение которых может быть самым разнообразным, что вынесение их всех в одну папку Interfaces, как мне кажется, затруднит поиск необходимого интерфейса. Я могу согласиться, что сделаться в папке View подпапку Inerfaces было бы логично. Но в данном маленьком проекте в папке View всего два интерфейса и два класса - не вижу смысла.
